# Changes here will be overwritten by Copier
_commit: v0.0.11
_src_path: gh:AmpelAstro/copier-ampel
author_email: jakob.van.santen@desy.de
author_name: Jakob van Santen
plugin_description: Astronomical catalog matching for Ampel
plugin_name: CatalogMatch
plugin_org: AmpelAstro
plugin_version: 0.10.0a1
version_cap: <0.11
