# Changes here will be overwritten by Copier
_commit: v0.0.12
_src_path: https://github.com/AmpelAstro/copier-ampel.git
plugin_description: Astronomical catalog matching for Ampel
plugin_name: CatalogMatch
plugin_org: AmpelAstro
plugin_version: 0.10.0a5
user_email: jakob.van.santen@desy.de
user_name: Jakob van Santen
version_cap: <0.11

#copier updated